# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
 
 
trigger:
- master
 
pool:
  vmImage: 'windows-2019'
 
steps:
# - pwsh: |
#    echo "##vso[task.prependpath]$env:CHROMEWEBDRIVER"
# - powershell: |
#    (Get-Item "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe").VersionInfo
# - bash: sudo chmod +x /home/vsts/work/1/s/IWECProject/drivers/chromedriver
#uncomment following for maven build
- task: Maven@3
  inputs:
   mavenPomFile: 'IWECProject/pom.xml'
   mavenOptions: '-Xmx3072m'
   javaHomeOption: 'JDKVersion'
   jdkVersionOption: '1.11'
   jdkArchitectureOption: 'x64'
   publishJUnitResults: false
   testResultsFiles: '**/surefire-reports/*.json'
   goals: 'clean compile test'
    #args: '' # Optional
    #disableAutoCwd: false # Optional
    #cwd: '' # Optional
    #failOnStandardError: false

- bash: |
    curl -H "Content-Type: application/json" -X POST "https://xray.cloud.xpand-it.com/api/v1/import/execution/cucumber" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnQiOiI2NmU0ZTA0OC04NDdiLTM1ZDktYjlhMy1iZjljYzg1MWM4ODQiLCJhY2NvdW50SWQiOiI1YWFiYjk4OTE4YzNiZDJhNzNmZWE3MDAiLCJpc1hlYSI6ZmFsc2UsImlhdCI6MTYwNzcxMTMyMywiZXhwIjoxNjA3Nzk3NzIzLCJhdWQiOiJCQzA0QTg1N0M2Nzg0M0IwODNGNTZDN0IzNUJFRERFRSIsImlzcyI6ImNvbS54cGFuZGl0LnBsdWdpbnMueHJheSIsInN1YiI6IkJDMDRBODU3QzY3ODQzQjA4M0Y1NkM3QjM1QkVEREVFIn0.rGMRrul03he8o5yc8GFuTmV3LGNSfozGXaHtwdT3hXc" --data @IWECProject/target/cucumber.json